### PR TITLE
team_traffic_simulator

### PR DESCRIPTION
**Pull request by gueralor**

### CODE REVIEW

**Comment by ltratt** [comment]
You need to lower case the team name and fix the repository name (you've pointed me to the master branch, which isn't the same thing).

**Comment by ltratt** [comment]
You need to rename the directory too.

**Comment by gueralor** [comment]
Which repository should I point you then?

2015-01-22 17:52 GMT+00:00 Laurence Tratt <notifications@github.com>:

**Comment by ltratt** [comment]
Have a look at those that have been merged for guidance.

**Pull request closed without merging**
