### PR TITLE
create team the_undecided

### PR DESCRIPTION
**Pull request by tonysellen**

### CODE REVIEW

**Comment by ltratt** [comment]
You're a person light -- you need exactly 5 members (not 4).

[Astonishingly, I have not heard that variant on my surname before. I am unsure whether to congratulate you or suggest that you drop any comedy career you might have hoped for.]

**Comment by tonysellen** [comment]
yes we know - working on getting another person.

Would you merge this (is that the terminology?)  and then let us edit the
members.txt later or do we need the 5 beforehand?

On 15 January 2015 at 18:24, Laurence Tratt <notifications@github.com>
wrote:

> You're a person light -- you need exactly 5 members (not 4).
>
> [Astonishingly, I have not heard that variant on my surname before. I am
> unsure whether to congratulate you or suggest that you drop any comedy
> career you might have hoped for.]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ltratt/7ccsmgpr_2015/pull/4#issuecomment-70134707>.
>



-- 
Tony Sellen
+447834352210

**Comment by ltratt** [comment]
You need to get all your ducks in a row (i.e. rope in a 5th person) before I can merge.

**Comment by tonysellen** [comment]
Ok sure

**Comment by tonysellen** [comment]
We have 5 members now and we have renamed the team.

best wishes

Tony Sellen

**Comment by ltratt** [comment]
In general, you're welcome to call the team whatever you want. I'm certainly a ripe target! For one reason or another, though, I'd prefer you chose a name which doesn't reference bad language. I'm not easily offended, but others are.

**Comment by tonysellen** [comment]
ok no problem.  We will think again

best regards

Tony

On 16 January 2015 at 17:52, Laurence Tratt <notifications@github.com>
wrote:

> In general, you're welcome to call the team whatever you want. I'm
> certainly a ripe target! For one reason or another, though, I'd prefer you
> chose a name which doesn't reference bad language. I'm not easily offended,
> but others are.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ltratt/7ccsmgpr_2015/pull/4#issuecomment-70292902>.
>



-- 
Tony Sellen
+447834352210

**Comment by tonysellen** [comment]
Dear Mr Tratt

I hope this is ok now.

Best regards

Tony Sellen

**Comment by ltratt** [comment]
I think the repository is wrong (shouldn't end in .git). The directory name should be lower case... and then we're good!

**Comment by tonysellen** [comment]
Hi again

Sorry to be so high maintenance!  I hope I've done it correctly this time

best regards

Tony Sellen

**Comment by ltratt** [comment]
Looks good!

**Comment by tonysellen** [comment]
cool thanks!

On 18 January 2015 at 14:18, Laurence Tratt <notifications@github.com>
wrote:

> Looks good!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ltratt/7ccsmgpr_2015/pull/4#issuecomment-70409793>.
>



-- 
Tony Sellen
+447834352210

**Pull request merged**
