### PR TITLE
Team brisk_new

### PR DESCRIPTION
**Pull request by k1455365**

### CODE REVIEW

**Comment by ltratt** [comment]
Is the deletion intentional?

**Comment by k1455365** [comment]
yes, previous version didn't with the postfix ".txt". is current version ok?

**Comment by ltratt** [comment]
There isn't a current version -- you deleted everything!

**Comment by k1455365** [comment]
what I delete previous is a branch I create under Itratt/7ccsmgpr_2015, should I create the brach under that, or in my own fork?

**Comment by ltratt** [comment]
If you need more help with git, you and your team mates will need to find it online. There are many resources available.

**Comment by k1455365** [comment]
could you please help us to delete this request and we try again.

**Comment by ltratt** [comment]
If you need more help with git, you and your team mates will need to find it online. There are many resources available.

**Pull request closed without merging**
