### PR TITLE
team_We_Got_This

### PR DESCRIPTION
**Pull request by RochelleA**
pull request

### CODE REVIEW

**Comment by ltratt** [comment]
I think you need to remove the ".git" from the repository name; other than that it looks OK.

**Comment by ltratt** [comment]
Oh, and the directory name should be lower case too.

**Comment by ltratt** [comment]
Just to be clear: these issues need to be fixed before your pull request is merged (and the team confirmed).

**Comment by RochelleA** [comment]
I have changed the team name and I believe I removed the .git before your email because I had changed it by mistake. Is this correct now?

**Comment by ltratt** [comment]
It still has .git in repo.txt...

**Comment by ltratt** [comment]
Looks good.

**Pull request merged**
