### PR TITLE
Update members.txt

### PR DESCRIPTION
**Pull request by JaySwang**
update the new member.

### CODE REVIEW

**Comment by ltratt** [comment]
Why has a member been deleted?

**Comment by JaySwang** [comment]
Sorry,but the new member should be Yamani Lujain, not Vasilishin Maxim.

**Comment by ltratt** [comment]
Unless that person has dropped off the course, they are a member of your team: you must have 5 members.

**Comment by JaySwang** [comment]
We do have 5 members. Vasilishin, Maxim is on the other team and Yamani, Lujain is the 5th member you allocated for us yesterday.

**Comment by ltratt** [comment]
Ah, I see. OK, looks good and merged.

**Pull request merged**
