### PR TITLE
pull 3

### PR DESCRIPTION
**Pull request by AlephKnull**

### CODE REVIEW

**Comment by ltratt** [comment]
You need to choose 1, and only 1, coordinator and you only need 1 blank line at the end of the repo.txt file.

**Comment by ltratt** [comment]
I should also note that the pull request can't be merged as is. You'll need to fix that too.

**Comment by AlephKnull** [comment]
ok. I will make the changes. 
Does that mean I need to close the current pull request, fix the files, then resubmit a pull req ?

**Comment by ltratt** [comment]
I've just noticed this is really a reissue of your first pull request (albeit with some of the excess deleted in later commits), so I'm going to close it for the same reasons I closed that one.

I suggest you a) reclone the 7CCSMGPR repo b) make the minimal changes to that c) issue a new pull request. This should be quick and easy.

**Pull request closed without merging**
