### PR TITLE
pull 1

### PR DESCRIPTION
**Pull request by AlephKnull**

### CODE REVIEW

**Comment by ltratt** [comment]
You need to actually fill in the repo.txt file...

**Comment by AlephKnull** [comment]
I have modified the repo.txt to


https://github.com/AlephKnull/7ccsmgpr_2015.git


Am I correct to assume that this is to be used as the url ?

After this change, should I make a second pull request ?

Anthony T.


________________________________

**Comment by ltratt** [comment]
Remove the ".git" and you should be OK.

**Comment by ltratt** [comment]
BTW, you'll need to tell me when you're ready to request me to look again.

**Comment by AlephKnull** [comment]
By closing the current request and submitting a new request ?

**Comment by ltratt** [comment]
Add a commit.

**Comment by ltratt** [comment]
I'm assuming this is finished.

**Comment by AlephKnull** [comment]
If I am in the cloned directory in my linux box, adding a commit amounts to the code 

git push origin master:ltratt/7ccsmgpr_2015

**Pull request merged**
