### PR TITLE
SignalGreen team request

### PR DESCRIPTION
**Pull request by asenf**

### CODE REVIEW

**Comment by ltratt** [comment]
You need to remove the ".git" from the repository name in repo.txt. Otherwise, looks good.

**Comment by asenf** [comment]
Done, thanks.

**Comment by ltratt** [comment]
Ah, the team name also should be lower case. Sorry.

**Comment by asenf** [comment]
I think that is done. As I didn't change my repository, the link in repo is still in caps. How's that?

**Comment by ltratt** [comment]
You need to rename the directory too.

**Comment by asenf** [comment]
Thanks for your patience. How's everything look now?

**Comment by ltratt** [comment]
Looks good.

**Comment by asenf** [comment]
Thank you!

On 22 Jan 2015 18:06, Laurence Tratt <notifications@github.com> wrote:

Merged #10<https://github.com/ltratt/7ccsmgpr_2015/pull/10>.

**Pull request merged**
