### PR TITLE
Fixed previous issues

### PR DESCRIPTION
**Pull request by ATsiopou**

### CODE REVIEW

**Comment by ltratt** [comment]
Why is there a new directory? It should be team_derive_and_conquer I think. If you can rename that, we should be good to go.

**Comment by ltratt** [comment]
And the repo.txt doesn't point to the right thing?

**Comment by ATsiopou** [comment]
On it. 
I couldn't rename the directory to team_derive_and_conquer, because that directory already existed. 
I will change the repo.txt as well. I just realized what was wrong.

**Comment by ltratt** [comment]
Delete the old directory then rename the new one.

**Comment by ATsiopou** [comment]
I think that may have fixed the issue ..

**Comment by ltratt** [comment]
And delete the old directory with capital letters please.

**Comment by ATsiopou** [comment]
Looks like its ready to go now ..  ?

**Comment by ltratt** [comment]
This is now almost right, but the repo.txt must point to the repository where you're doing your development (not to the clone of the 7CCSMGPR repo).

**Comment by ATsiopou** [comment]
changed the repo. It now points to simulation (i left the .git on the end?)

**Comment by ltratt** [comment]
If you can remove the .git, then we're done!

**Comment by ATsiopou** [comment]
:) all done !!

**Pull request merged**
